# Generated by Django 4.0.5 on 2022-08-12 01:49

from django.db import migrations, models
import django.db.models.deletion
import healthtracker.models.readings


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatinineChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Check status')),
                ('lower_danger', models.FloatField(blank=True, null=True, verbose_name='Lower danger bound')),
                ('lower_ok', models.FloatField(blank=True, null=True, verbose_name='Lower ok bound')),
                ('upper_ok', models.FloatField(blank=True, null=True, verbose_name='Upper ok bound')),
                ('upper_danger', models.FloatField(blank=True, null=True, verbose_name='Upper danger bound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlucoseChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Check status')),
                ('lower_danger', models.FloatField(blank=True, null=True, verbose_name='Lower danger bound')),
                ('lower_ok', models.FloatField(blank=True, null=True, verbose_name='Lower ok bound')),
                ('upper_ok', models.FloatField(blank=True, null=True, verbose_name='Upper ok bound')),
                ('upper_danger', models.FloatField(blank=True, null=True, verbose_name='Upper danger bound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthtracker.timestamp')),
            ],
            options={
                'abstract': False,
            },
            bases=(healthtracker.models.readings._BaseReading, models.Model),
        ),
        migrations.CreateModel(
            name='Creatinine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthtracker.timestamp')),
            ],
            options={
                'abstract': False,
            },
            bases=(healthtracker.models.readings._BaseReading, models.Model),
        ),
    ]
