# Generated by Django 4.0.5 on 2022-08-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0002_creatininechecker_glucosechecker_glucose_creatinine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='days_left',
        ),
        migrations.AddField(
            model_name='individual',
            name='goal_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
